image: go1.2
env:
  - GOPATH=/var/cache/drone

script:
  - go test -v
  - mkdir -p stage
  - pwd
  - GOOS=linux go build -o stage/busybox-go-webapp

deploy:  
  bash:
    script:
      - chmod 600 ./.drone/id_rsa
      - tar --exclude=".drone" --exclude=".git" --exclude="*.tar.gz" -zcvf busybox-go-webapp.tar.gz .
      - scp -i ./.drone/id_rsa busybox-go-webapp.tar.gz deployer@10.1.1.3:/tmp/apps/