image: go1.2
env:
  - GOPATH=/var/cache/drone

docker:
  volumes:
    - /tmp/apps:/tmp/apps

script:
  - go test -v
  - mkdir -p stage
  - pwd
  - GOOS=linux go build -o stage/busybox-go-webapp
  #- cp stage/busybox-go-webapp /tmp/apps/busybox-go-webapp-test
  
deploy:  
  bash:
    script:
      #- chmod 600 .drone/private_deploy_key
      - scp deployer@10.1.1.3:/tmp/apps stage/busybox-go-webapp